### ISSUE TITLE
ENHACEMENT - Way to format (thousand separator) 

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#132]

**Comment by atl2017** [comment]
It was included in ODK Colect v1.12

**Comment by nap2000** [comment]
Excellent. I am moving to a close on my current urgent project and will
hopefully get the upgrade to odk 1.12 out early next week.  Nice new
features coming your way include:

   - A new xlsForm template loader that also loads security roles,
   parameters, key policy etc and preserves list names.
   - The xlsForm loader now also supports shared tables which I am calling
   "groups" - makes the concept much more usable for sharing data with follow
   up tasks
   - In tasks you can assign a task to all users with a specific security
   role rather than to a specific user
   - You can also assign tasks to user idents or roles that are specified
   in the data.  Ie if you have a data item region and the user entered
   "calli" you can assign the new task to all users that have the security
   role "calli"
   - You can specify that tasks apply to either data already collected or
   to future data yet to be submitted or to both.  I had to add this as there
   were tables with thousands of submissions and I wanted to create tasks just
   for new submissions.

Lots more nice new features too.

Back to testing

**Comment by atl2017** [comment]
Great News!  I traslated all pending in transifex:

Maybe you could also considering messages like:

![image](https://user-images.githubusercontent.com/29519901/34202332-78d5ca14-e545-11e7-81b9-b93f1b29c86f.png)

**Comment by nap2000** [comment]
Already done.

**Comment by atl2017** [comment]
Tested OK in FT, but pending in PDF

**Comment by atl2017** [comment]
Is it possible to include in PDF formating?

**Comment by atl2017** [comment]
Not big deal
