### ISSUE TITLE
BUG - 17.12 - Roles are not working in Analysis

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#175]
### Actual Behaviour: Either as Analysist or View Data Security Group, data are not displayed if it is restricted with Role in Analysis. As enumerator it works fine. I mean, form is displayed in FT.

![image](https://user-images.githubusercontent.com/29519901/35354115-248b371c-0117-11e8-8907-da28abcc45e9.png)

### Form Name: TestRol and TestRole 2    Role: Rol2

![image](https://user-images.githubusercontent.com/29519901/35354295-9b6e2f92-0117-11e8-800d-85bf922c98a5.png)

**Comment by nap2000** [comment]
I'm not sure what the issue is here.  Does the user have Rol2? If not then they should not be able to see any data in that form. They should not in fact be able to see the form at all.  The exception would be when the user has securityManageRole.  In that case they can see all forms and their data even if they do not have Rol2.   When exporting data however the roles are applied even for security managers.

**Comment by atl2017** [comment]
Hi Neil,

I tested with this user that has the role

![image](https://user-images.githubusercontent.com/29519901/35383978-e84c2704-0191-11e8-9765-bd3ef17b92d4.png)

And what is displayed:

![image](https://user-images.githubusercontent.com/29519901/35384039-1004b2f2-0192-11e8-88c3-c5aadca1a692.png)

**Comment by atl2017** [comment]
Tested Ok. Thanks
