### ISSUE TITLE
HIGH - BUG - 18.01 Analysis : When filter by date, some records are repeated

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#186]
### Actual Behaviour: Table show duplicate records when filter is applied:

![image](https://user-images.githubusercontent.com/29519901/35841731-8b188774-0acb-11e8-9bf1-bdbfb24192da.png)
![image](https://user-images.githubusercontent.com/29519901/35841761-b2f110ae-0acb-11e8-9fc2-cc29b42c6b1b.png)

**Comment by nap2000** [comment]
This was happening because the date being filtered on "FechaCierre" was in a sub form.  Hence there was a row shown for each row in the subform.

For the analysis table view there was an easy fix to only show distinct / unique records of data.   I made this change so hopefully you won't see the duplicates there any more.  However if you are exporting just the top level table and you filter by data in a subform then you will still see the duplicates.   It would be more difficult to provide a fix in these cases as the export may not include primary key or other unique data and hence removing duplicate rows may remove valid records that just happen to be the same as another record.

Another problem with filtering on questions in a sub form is that if that subform was not called for a survey then you won't see any data which is presumably what you want though.

In this case the filter was a date.  If you can filter on a date in the top level form then you won't have these problems.  Ie Upload time, start time, end time or any data question added to the top level form.

**Comment by atl2017** [comment]
Interesting.  There are also some improvements in UX that we can also consider:

1- Maybe Date and Filter by Dates should be together in order to be concious what date are being considered for.

2- Dates by default are listed in A-Z, so the first date could be like in this case a date from a subform. I suggest to consider the following logical order based on time series:
    a- _start or renamed question (in my case: Hora Servidor)
    b- _end
    c- _upload_time
    d- dates in subforms
3- Highlight Date with a background color like yellow
4- (For me) to be concious of these constraints and name questions accordingly.

![image](https://user-images.githubusercontent.com/29519901/35856159-1e6dd2a4-0b03-11e8-8c1c-799176967b9e.png)
