### ISSUE TITLE
BUG - API csv do not consider new key policy: merge

### ISSUE THREAD

**Issue by ztatu** [smap-consulting/smapserver#29]
### Steps to reproduce the problem

(Optional) If this is reproducible on a Smap hosted server then include

### Form Name: 1 - Prestamo

Check : [ CSV](https://app.kontrolid.com/api/v1/data.csv/2936)  vs. [JSON: ](https://app.kontrolid.com/api/v1/data/2936)

**Comment by nap2000** [comment]
The CSV API returned all data including those records marked as bad.  It does not however include the _bad column and _bad_reason columns that would have shown that a record had been merged.  Briefly I considered adding those so that a user could track changes to the data through this call.  

However that is probably not the behaviour a user would expect from the kobo api.  Currently the only place where you can review merged data is in the old analysis module in the table view.  Probably we should add a data history view and maybe an option to the kobo API to request historical data.

In the interim the code has been updated to only return the current valid data for the CSV call.  This will be included in the next 17.06 minor release due on 15th July 2017.

**Comment by ztatu** [comment]
I agree. It could be interesting to have historial data including all _bad and _bad_reason columns through an option in API.

**Comment by nap2000** [comment]
Well yes.  Although more important than interesting would be if there was a use case for reviewing and auditing changes.

**Comment by ztatu** [comment]
Tested OK
