### ISSUE TITLE
BUG - REPORTS - Delete does not produce any results

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#294]
### Actual Behaviour: Delete does not produce any results in Reports

![image](https://user-images.githubusercontent.com/29519901/40806230-7b15405e-64e6-11e8-8831-187bf7342ba8.png)

**Comment by atl2017** [comment]
What is happening is that deletion occurs but you do not see any action after refresh. You see results if you goes out page and return.

![image](https://user-images.githubusercontent.com/29519901/40807541-356e7184-64ea-11e8-8a4c-b8b5ba888067.png)

**Comment by nap2000** [comment]
I could not reproduce this error, the report was removed when I tried this.  In my test I:

- Started with an empty report list
- Added a report
- Select delete
The report was then removed from the list.  Possibly the circumstances causing this error are more complex.  Can you open the javascript console.  In Chrome this is from the chrome menu "view > Developer > Javascript console".  Then repeat the delete and see if there is an error shown in the console.  If so please paste that error into the bug report.  If it is not chrome that you are using what browser is it?

**Comment by atl2017** [comment]
Tested in Chrome and Firefox and both fails:

![image](https://user-images.githubusercontent.com/29519901/40874173-ae0eff94-6631-11e8-99f1-0dd83b1d4ed8.png)

[Video Recording with javascript console](https://www.useloom.com/share/33793634a326410ab9c7ccecbf476dca)

[Video Recording only](https://www.useloom.com/share/c8926903ec41492884d95ef702d5a811)

**Comment by nap2000** [comment]
The table list was being automatically refreshed.  The problem was that the delete of the report was taking well over a minute.  This was because reports are basically a temporary user who can only generate the report.  This allows you to send the link to someone without a logon. When you delete a user then all of the data associated with that user is also deleted including the user trail.  None of these temporary users that are created for reports would have any use trail data but the delete had to go through 55 million records just to make sure.   

I've added an index to the user id on that table now so the delete of users is now down to 2 milli seconds.  You should also find that viewing user trail data is now a lot faster.

**Comment by atl2017** [comment]
Tested OK. You are really very smart to find and fix root cause.

I misunderstood "User trail data" and thought it was "Usage".  That reports still crashes:

![image](https://user-images.githubusercontent.com/29519901/40886937-643e04c0-6706-11e8-858a-6a0c33ab7af6.png)
