### ISSUE TITLE
BUG - Note widget does not recognize question name.

### ISSUE THREAD

**Issue by ztatu** [smap-consulting/smapserver#30]

**Comment by nap2000** [comment]
I think this is already fixed.  

In the form you were testing the referencing of a question answer or calculation from a label was not working in the case where the question with the label was loaded from an XLS file.  Questions added from the online editor did not have the problem.  

Possibly this problem was introduced in a recent update which has since been resolved.  However forms loaded while the bad update was in place will still show the error.

I exported the original survey as XLS and then reloaded it.  The note then showed correctly in the newly loaded form. Hence I think the problem is fixed.   

As a work around to any forms that exhibit this issue, you can use the online editor to add a space any labels with the problem and save.  It should then work.  I did this with the Horas ExtrasVr1 form.

It is possible that there is a more subtle problem related to the way that you created "Nota2".  Ie using cloning?   If you can reproduce this raise a new issue including all the steps used to create the problem.

**Comment by ztatu** [comment]
Tested OK
