### ISSUE TITLE
BUG - Data deleted after some records with linked_self 

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#35]
### Actual Behaviour 
![screenshot-1500058794466](https://user-images.githubusercontent.com/29519901/28226877-4fe32ce8-689d-11e7-8968-e9764d03670a.jpg) after few surveys filled

### Steps to reproduce the problem

Input some IDs (You can test with 8690002, 91440603, 64579240 or look at Empleados.csv at Shared Resources

**Comment by ztatu** [comment]
Same situation happen with:

server: kontrolid
organisation: DEMO
project: Lavadero
form: Lavadero2

Data is erase at phone. It is fixed by erasing form and refreshing again, but after one survey is filled situation happened again.

Steps to reproduce the problem:

You can enter as Placa: HZS246 or Abc123 or a new one (3 letters 3 numbers).

Please is URGENT

**Comment by nap2000** [comment]
Steps taken to test:

1. Refreshed phone using a user that had access to the TestAlex project
2. Opened form, selected "In" and entered "8690002" as the ID
---- No error was reported
3.  I continued to test submitting multiple instances and could not reproduce the error.

I've marked the issue as invalid mainly because there is inadequate information supplied.  Ideally the steps should allow the issue to be reproduced.  If the problem is intermittant then can you supply a more full description, at minimum what you are doing when the problem occurs, ie pressing the save button or opening a form for completion etc.

**Comment by ztatu** [comment]
Thanks. @nap2000 . Apparently I can reproduce the situation. It happens when I tried to force updating refresh button instead of wait autosend.

**Comment by nap2000** [comment]
Ok.  
1. Does the problem occur if you don't only do manual refreshes.  That is what I used to try and reproduce.  
2. Is this a problem that only occurs when you use both automated and manual refreshes.  
3. If the answer to 2 is yes, does it always happen or is there some kind of timing issue where you press the manual refresh while an auto refresh is in progress?

**Comment by ztatu** [comment]
a- Always happens after manual refreshing to send finished form.
b- After autorefresh is OK.

Maybe situation is related that both process are different. What I see is manual refresh include updating .csv files.

**Comment by ztatu** [comment]
Confirmed. It is caused by:

a- Always happens after manual refreshing to send finished forms.
b- After autosend is OK

**Comment by atl2017** [comment]
Due to new release with automatic refreshing, this issue needs to be  re-checked and raise a new issue in case of it continues.
