### ISSUE TITLE
URGENT - H1 - Screen blocks when try to create or edit a new notification

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#350]
### Steps to reproduce the problem

Just create a new notification in any project. Tested with Chrome and Firefox

**Comment by nap2000** [comment]
I haven't been able to reproduce this.  Can you provide details of the steps you took.  If nothing happens when you press the ok button then its possible there is an error in the javascript in the form.  So if you show the developer console an error may be displayed there which would be useful to know.

**Comment by atl2017** [comment]
I repeated the process with second notification in below list. I could edit Notification, EXCEPT, when I add the THIRD email. When I added second or change other element of the sonitifcation, I could save.

![image](https://user-images.githubusercontent.com/29519901/43722632-534630e8-995b-11e8-9672-95ecf3835bc7.png)

**Comment by atl2017** [comment]
It is happening again
