### ISSUE TITLE
H2 - ENHANCEMENT - PDF - Dynamic notification based on name question

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#43]
### Expected Behaviour:
Similar to Email Question, include a Notification Question (yes/no true/false) that enable /disable notification based on it.

![image](https://user-images.githubusercontent.com/29519901/29031924-60e948e0-7b55-11e7-90a3-ef2495364218.png)

### Why is important?
- You can redirect webform/pdf/sms based on it
- You can simulate "workflow" and include pdf only after revision has been accomplished

**Comment by ztatu** [comment]
### Steps to reproduce the problem

(Optional) If this is reproducible on a Smap hosted server then include

### Server: Kontrolid

### Organisation: COLVISEG

### Project: Tecnicos Seg. Electr

### Form Name: Analisis Trabajo Seguro

Survey is accomplished in two steps (by two users) one by FT and the other by webform. PDF notification is sent TWICE after each step is accomplished

### Expected Behaviour: Just ONE notification after full survey completion. Solution:  Include an Able/Disable question. In this particular case I could use if ${Step}=2 then Send Email

**Comment by atl2017** [comment]
A typical use is when a submitted form needs to be sign for an upper supervisorn in order to complete authorisation. Current way implies to generate PDF as evidence  and send it for both issuer and supervisor. Simultaneously, send webform link to supervisor in order to complete authorisation with signature. Again a PDF is sent for both issuer and supervisor to confirm process have finished.

Along with #45 could improve this process.

**Comment by atl2017** [comment]
@nap2000  I have tested "Forward" notification. It is also perfect to include in this kind of dynamic in order to send only some records instead of all. Today it works as a copy

**Comment by atl2017** [comment]
@nap2000  Currently I need this feature because I have the challenge to redirect two pdf. A form captures different data if it is a new customer or not and customised pdf are different based on that.

**Comment by atl2017** [comment]
Thanks a lot for recent features!
