### ISSUE TITLE
ENHANCEMENT - Url PDF generator

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#443]
### Expected Behaviour
A customer is using Kontrolid as server avoiding users access directly to our analysis dashboard. They are interested to have an API or web service that let generate a related PDF based on Form ID + Key in order to embed this url in PowerBi Dashboard and to have access to an specific issue:
![1](https://user-images.githubusercontent.com/29519901/54400343-5a8dfb00-4690-11e9-9445-8aa6089851da.png)

**Comment by nap2000** [comment]
Updated with the following changes:
   1) Added documentation for creating an API call that will return a PDF.  http://www.smap.com.au/apiIntro.shtml#pdf_submission
  2) Added documentation for creating an API call that will open a submission in a Webform. http://www.smap.com.au/apiIntro.shtml#webform_submission
  3) Added a new parameter links=true,  to /api/v1/data/{survey ident}?links=true.  This will then, for each record, include preformatted links for getting a PDF or opening a submission in a web form
  4) Modified /api/v1/data so that for each end point returned a links=true parameter is automatically added.

**Comment by atl2017** [comment]
Great. But links fails because add extra slashs:

Example:
"links":{"data":"https:\/\/app.kontrolid.com\/\/api\/v1\/data\/s451_10638\/uuid:6e4a817f-1772-4477-a155-df289fae7627"

![image](https://user-images.githubusercontent.com/29519901/56876282-eaeb8980-6a0b-11e9-85d8-f85f8b8d94fa.png)

**Comment by atl2017** [comment]
Also, in order to avoid additional step, is it possible to set  UTC in PDF link as set in Organisation settings? (i.e https://app.kontrolid.com/surveyKPI/pdf/s299_10827?instance=uuid:81102a9d-65aa-4c97-8995-984af9c757a8&tz=UTC)

**Comment by atl2017** [comment]
Corfimed with direct access in Excel: There is an extra / after .com in all links:

![image](https://user-images.githubusercontent.com/29519901/57113718-81b98e00-6d0b-11e9-914d-64638a0fa322.png)

**Comment by nap2000** [comment]
Updated to remove the extra "/"
If timezone is not specified it will now default to the organisation timezone

**Comment by atl2017** [comment]
Tested Ok. Thanks
