### ISSUE TITLE
ENHANCEMENT - Fast way to access form id

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#472]
### Expected Behaviour. Many times you have to check a for id to use with linked form, launch forms, etc. To do that, currently you have to list, click in forms and -> File ->Settings or Info to get that information. There is some risk of accidentaly change a form or just there are many steps related.

My proposal is just to include ID as part of the list:

![image](https://user-images.githubusercontent.com/29519901/57313947-3e1da600-70b6-11e9-89b5-d0d2d8c44668.png)

![image](https://user-images.githubusercontent.com/29519901/57313877-162e4280-70b6-11e9-9e27-6180211bd7c5.png)

**Comment by nap2000** [comment]
I tried this one out and it clutters up the user interface.  Because of that I don't think it adds enough value.  If you are using the online editor the forms should be pickable from a list.  This has started to happen with search() and launching forms.  When using the xlsForm editor there is a little bit more work to select the survey and view its info but I think that is a reasonable trade off.

**Comment by atl2017** [comment]
Understood. Thanks.
