### ISSUE TITLE
L16 - ENHANCEMENT - MONITORING - Alert by Email in case of error

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#49]
### Actual Behaviour: Monitoring is a good way to check for error, but you need to check periodically to detect any issue. So it is possible that an error happens many dyas until someone detect failure.

![image](https://user-images.githubusercontent.com/29519901/29150578-234cd63a-7d41-11e7-8cc5-a8a64f4f1d24.png)

**Comment by nap2000** [comment]
Real errors are actually pretty rare.  The most common problem on data submissions are reported directly to the phone user as survey not found.  Ie they survey that they were completing has been deleted or blocked on the server.  The user is immediately notified of this issue as an error on the phone.  I could send an email alert on these however.

What I call a real error is when a survey is successfully submitted from the phone but there is some kind of issue with the survey definition and when the system attempts to write the data to the database it fails.  These are the errors that can stay hidden for days until someone asks where there data has got to.  So yep it could be a good idea to alarm these.

However the example you provide is a bad one since there is an error with the email server so it would be pointless to send an email about that.  Having said that I can sent up a separate AWS based publish subscribe that you can subscribe to for alerts as SMS or email.  So could be ok,

**Comment by ztatu** [comment]
I agree with your comments above. My examples are related specifically with notifications and of course if there is a situation with email server we should alert by another channel or server. I mean, Error is known by Monitoring.  My suggestion is to send an alert email (maybe using server smtp) instead of organisation server to communicate to organisation's email that errors have been found.

**Comment by atl2017** [comment]
Hi Neil,

I have face different situation in different organisations as below: What could be a solution to monitor that email was not sent in a proactive way. Like an alarm report. It could be for all organisations or by organisations.

![image](https://user-images.githubusercontent.com/29519901/33284492-475e2168-d37d-11e7-9e15-bf0dfa59a273.png)

![image](https://user-images.githubusercontent.com/29519901/33284732-0590d96e-d37e-11e7-8c49-6de57c1a6f15.png)

![image](https://user-images.githubusercontent.com/29519901/33284783-39c046de-d37e-11e7-8761-dc7bd53a9f4d.png)

**Comment by atl2017** [comment]
Hi Neil,

Happened again,

A customer haven´t received any email from notifications due to change in SMTP account settings TODAY. I noticed because I send a notification to me, but it could be good to have an alert system that send a error message 

![image](https://user-images.githubusercontent.com/29519901/35174216-8a5d0b80-fd3c-11e7-943f-f8d5594c4e32.png)

**Comment by atl2017** [comment]
Neil, thanks a lot for a way to resend notifications. Maybe to support this as mention above is just to include an alert system by Email using SMTP Server settings (not organisation)  triggered by the same way  let "Retry" button be included. I meant, when the "Retry" button is created then triggered an alert email

![image](https://user-images.githubusercontent.com/29519901/35509657-01c76340-04c3-11e8-8c04-775a19488445.png)
