### ISSUE TITLE
SMAP - ENHANCEMENT - Add a blank choice in key policy so the filter can be cleared

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#529]
### Actual Behaviour: We can only choose from one standard policy:
![image](https://user-images.githubusercontent.com/29519901/65921783-d9d2ea00-e3a8-11e9-8fdd-ca4b9692e37e.png)

![image](https://user-images.githubusercontent.com/29519901/65921825-f8d17c00-e3a8-11e9-91b9-897820f55a71.png)

**Comment by nap2000** [comment]
**This initial change only affects the survey key policy and not the key policy for an individual form**

1) An option of "none" has been added to the editor.  Valid key policies are now:
- none
- discard
- merge
- replace
2) When loading a survey from XLSForm it now checks for a valid key policy
3) Change in behaviour (relatively minor)

Previously if a survey had an HRK then the key policy was applied even if a direct update to the record was being performed.  Ie a task was sent to update a record or you selected edit in webform from the console / dashboard.  Now if you do these direct updates the record will always be replaced irrespective of the key policy.  The key policy is only used when a new record is submitted and the survey uses HRKs.

Previously if a survey had an HRK then the default key policy was "replace".  This prevented the survey from accumulating duplicates.  Now (since we have the concept of setting a key policy to "none") if the key policy is none then the record will be append creating a duplicate entry.

Refer to:  http://www.smap.com.au/docs/keys.html

**Comment by nap2000** [comment]
Key policy for individual forms has now been updated to include the option of select "none".  This has been released on the SG server.   The default action of not setting a key policy is to "append" new sub form records.  Hence selecting "none" has the same effect as selecting "append".

Refer to: http://www.smap.com.au/docs/sub_form_kp.html

**Comment by atl2017** [comment]
Tested OK
