### ISSUE TITLE
Enhancement - Allow users to accept unassigned tasks

### ISSUE THREAD

**Issue by nap2000** [smap-consulting/smapserver#538]
1. Add checkbox on task group that when set allows users to select unassigned tasks
2. If afore mentioned checkbox is set then unassigned tasks will be downloaded to devices
3. Unassigned tasks will appear after assigned tasks so if the user has a limit of 10 tasks and they already have 10 tasks assigned then no unassigned tasks will appear
4. A user can select and complete unassigned tasks like any other tasks
5. If more than one user completes an unassigned task then the same procssessing will be applied as is done for tasks assigned to multiple users
6. For long running tasks the user can "accept" an unassigned task.  This task will then be assigned to them.

**Comment by atl2017** [comment]
Great.  I supposed 5. refers to apply policy set in "Complete all" check/uncheck.

**Comment by atl2017** [comment]
Tested in 4 differents devices/users. Project: TestTasks  TaskGroup: SelfAssignedCompleteAllTRUE 
Comments:
1- Synchronisation is not automatic. It is needed to refresh manually to see unassigned tasks.
2- Complete All = true does not take any effect.
3- Perhaps due to 1- Everyone can self assign same task. There would be a potential conflict between completed tasks:
![image](https://user-images.githubusercontent.com/29519901/68688754-570f8400-053d-11ea-952e-0ca335145d5f.png)
4- When click in unassigned task, message in notification text(Toast) is like message when try to resend a sent form. I would reccommend to change to "Unassigned task, click to assign yourself or reject"
![WhatsApp Image 2019-11-12 at 7 43 21 AM](https://user-images.githubusercontent.com/29519901/68689370-3a278080-053e-11ea-89f8-42f40262a8e5.jpeg)

**Comment by atl2017** [comment]
Hi Neil,

The  most important issue is related with synchronisation and how to prevent duplicates conflict.
