### ISSUE TITLE
8- ENHANCEMENT - Standard PDF - Hide user - instance name and others

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#599]
### Expected Behaviour: Taking into consideration pdf reports usability we would like to propose the following changes, that could permit more elegant standard pdf reports:
1. Change title from Form name to Instance name
2. Eliminate Project
3- Eliminate prikey and Key
4- Eliminate prikey in subforms
5- Eliminate item number in subforms
6- Hide label after the second record in subforms. Only display first record header. That could permit design beautiful tables

![image](https://user-images.githubusercontent.com/29519901/80777658-8fc30a00-8b2b-11ea-9c33-42e75e3e35c3.png)
![image](https://user-images.githubusercontent.com/29519901/80777921-59d25580-8b2c-11ea-9448-82c7809b2e9b.png)

**Comment by Rajen2020** [comment]
Hi Neil,
Can this feature be used now in sg.smap.com.au server? Or, I need another separate server to use this feature. Since one doesn't know how many repeats can be there in a subform, so we cannot use a customized pdf template practically. Kindly.

**Comment by nap2000** [comment]
Hi Rajendra,  Yes this feature is available on the SG server and all other servers.   I shall now prioritise this issue.

**Comment by nap2000** [comment]
All of these changes have been done:

1) Prikey removed
2) Added pdfhideindex appearance on "begin repeat" to hide the repeat index
3) Removed project
4) Set the title to instance name (survey name if instance name is not set)
5) Added pdfhiderepeatinglabels as an appearance for questions inside a begin repeat.  Use this so that only the first label in a set of repeating records is shown.  You will probably want to add it to all the questions in the repeat.

[Here is a sample form with the new appearance settings.](https://docs.google.com/spreadsheets/d/1QXSmGGPntkY0uaN8vYe97i51IZjlFfCBDSBKaKT22tM/edit?usp=sharing)

I have not added support for the new appearance settings in the online editor but they are in the documentation

**Comment by atl2017** [comment]
Tested Ok. Excellent work!

![image](https://user-images.githubusercontent.com/29519901/85854580-46351b00-b77a-11ea-878d-efdb027f3acc.png)

**Comment by Rajen2020** [comment]
Hi Neil, 
Really excellent work, nearly no need to use customized pdf template for my projects in regards to using repeating subforms. Thanks to you Neil, and atl2017 for this. However, **field-list** option to seeing all questions under a repeating subform in a single page of FieldTask doesn't seem to work together with pdfhideindex option in case of that neither we keep **pdfhideindex** before field-list nor after. I hope, while adding online editor support, this should be considered for looking into! I think field-list option for both the normal group and repeating group is great option for data enumerator.

**Comment by Rajen2020** [comment]
Thanks, Neil for your trick regarding field-list, that worked. One related issue regarding the use of **pdfhiderepeatinglabels** for generating beautiful subform data table, I think colon sign right at the end of label should be able to hide/remove. Beacuse for that type of table format, **colon sign would have no significance**.

**Comment by atl2017** [comment]
Really great!

1- Is it possible to hide instancename if it is set as title?
2- Is it possible to hide user because it is include as footer?
3- What about include timestamp  Created: yyyy-mm-dd hh-mm ( Upload time)
                                                        Printed:  yyyy-mm-dd hh-mm ( Now when download)

![image](https://user-images.githubusercontent.com/29519901/86846734-e8091180-c070-11ea-9503-d1983db4b352.png)

**Comment by Rajen2020** [comment]
Good idea, atl2017. However, if possible the 'Completed by' at the footer of report should be optional while setting the form. Because, sometime the printed copy of generated pdf should have another signatures like, 'Prepared by' or/and 'Approved by' etc. So, we need to put those phrases for places to get the signatures.

**Comment by Rajen2020** [comment]
I would take another liberty here to suggest little but important enhancement in the generated pdf. Would it be possible to make the value **bold** like label? Because, say- **Grand Total** and **250,000.00** (say) should be displayed in bold.
