### ISSUE TITLE
FUTURE - ENHANCEMENT - STANDARD PDF - PART 4 : Numeric Format

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#637]
### Expected Behaviour

To include some numeric formatting like decimal and thousand separators, money sign, bold and italics for values

@Rajen2020

Rajen2020 commented 11 days ago •
I would take another liberty here to suggest little but important enhancement in the generated pdf. Would it be possible to make the value bold like label? Because, say- Grand Total and 250,000.00 (say) should be displayed in bold. At least for numeric value!

**Comment by Rajen2020** [comment]
Thanks. Hope to see all latest features in my server also.

If we can set Display Name also for calculate type of field, would be super! This is partly relevant in this thread because, while we are developing questionnaire we use field name that can be easy to remember and refer, but in generated pdf report, those calculated fields look uneasy, maybe ugly sometimes. Hope my point has sense to developer team also.

**Comment by Rajen2020** [comment]
I ask and encourage developer team of SMAP to work out the numeric format in the upcoming server enhancements.
