### ISSUE TITLE
ENOENT. No such file or directory

### ISSUE THREAD

**Issue by ztatu** [smap-consulting/smapserver#8]
### Steps to reproduce the problem: It occurs with some frequency and apparently is when you assign an instance name and you switch from users at FT.

![instancename](https://user-images.githubusercontent.com/29519901/27296439-708a5f0e-54e6-11e7-80de-7aff4f8bb2d0.jpg)

**Comment by nap2000** [comment]
Hi Alexander.  Can you claify what you mean by switch from user?

**Comment by ztatu** [comment]
Hi Neil. Just using one user and then change to other user with the same device. I do all time for testing purposes. What I saw is that using instance name is common to find ENOENT first time after sending a form to server . It is fixed automatically second time  a form is filled out. It is like first time do not find a file and then create it.

**Comment by nap2000** [comment]
@ztatu I haven't managed to reproduce the problem. If you could provide a series of steps that will generate this error that would be good.  

Otherwise the next time it happens some of the following contect would be useful: are you using the refresh button,  deleting forms, deleting instances. Is the instance from a form that is in a common project for the two users, or only accessible to user 1 or only accessible to user2.

**Comment by ztatu** [comment]
I am not sure but, maybe it should be related to issue #35
