### ISSUE TITLE
BUG - started repeated tasks re not shown after manual refresh

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#92]
### Expected Behaviour: After manual refreshing or updating FT with new release, repeated tasks should be displayed no matter how many times have been completed .

![image](https://user-images.githubusercontent.com/29519901/30644316-9db44b9a-9dd7-11e7-8852-036917b7aec2.png)

### Actual Behaviour: After updating FT version and push refreshing Tasks, only forms and non periodic tasks are shown (due to started repeated task have submitted status):

![image](https://user-images.githubusercontent.com/29519901/30644331-a877c6ce-9dd7-11e7-9c63-f2cb435d33ad.png)

What I need to do to see all tasks is to reset to zero (accepted)

![image](https://user-images.githubusercontent.com/29519901/30644344-b2caf18c-9dd7-11e7-8e8f-0a63e7e7095d.png)

### Steps to reproduce the problem
Create repeated forms, accomplish more tan one and refresh manually in FT

**Comment by nap2000** [comment]
Are you saying repeated tasks are removed from the phone after you press refresh.  If so that is not the behaviour I am seeing.  Can you provide more detailed steps that will allow me to reproduce.

On the server it already shows repeated tasks with a repeat count of how many times they have been submitted.  As soon as a task is submitted once its status will change from accepted to submitted.  The repeat count will then increment with each new submission.

Because the status of the repeating task has been changed to submitted on the server after the first submission if you delete all the saved forms on the phone and refresh it will not re-download the repeating task.  A new repeating task will need to be created.

**Comment by atl2017** [comment]
You are right. I deleted save forms. Because of new automatic refreshing, I forgot that repeated tasks remains as saved form.

We need to be cautious when using repeated tasks and be sure to hide ODK menu.
